/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiRouteImport } from './routes/ai'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as SystemsRouteImport } from './routes/systems'
import { Route as SystemsIndexRouteImport } from './routes/systems.index'
import { Route as SystemsAuraHospitalityRouteImport } from './routes/systems.aura-hospitality'
import { Route as SystemsCivicPulseRouteImport } from './routes/systems.civic-pulse'
import { Route as SystemsConstructXRouteImport } from './routes/systems.construct-x'
import { Route as SystemsEquinoxLedgerRouteImport } from './routes/systems.equinox-ledger'
import { Route as SystemsForgeMesRouteImport } from './routes/systems.forge-mes'
import { Route as SystemsNexusCampusRouteImport } from './routes/systems.nexus-campus'
import { Route as SystemsPrismImpactRouteImport } from './routes/systems.prism-impact'
import { Route as SystemsPulseOsRouteImport } from './routes/systems.pulse-os'
import { Route as SystemsStrataOpsRouteImport } from './routes/systems.strata-ops'
import { Route as SystemsTalentGridRouteImport } from './routes/systems.talent-grid'
import { Route as SystemsVectorDispatchRouteImport } from './routes/systems.vector-dispatch'
import { Route as SystemsVeloxCommerceRouteImport } from './routes/systems.velox-commerce'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsRoute = SystemsRouteImport.update({
  id: '/systems',
  path: '/systems',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsIndexRoute = SystemsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SystemsRoute,
} as any)
const SystemsAuraHospitalityRoute = SystemsAuraHospitalityRouteImport.update({
  id: '/aura-hospitality',
  path: '/aura-hospitality',
  getParentRoute: () => SystemsRoute,
} as any)
const SystemsCivicPulseRoute = SystemsCivicPulseRouteImport.update({
  id: '/civic-pulse',
  path: '/civic-pulse',
  getParentRoute: () => SystemsRoute,
} as any)
const SystemsConstructXRoute = SystemsConstructXRouteImport.update({
  id: '/construct-x',
  path: '/construct-x',
  getParentRoute: () => SystemsRoute,
} as any)
const SystemsEquinoxLedgerRoute = SystemsEquinoxLedgerRouteImport.update({
  id: '/equinox-ledger',
  path: '/equinox-ledger',
  getParentRoute: () => SystemsRoute,
} as any)
const SystemsForgeMesRoute = SystemsForgeMesRouteImport.update({
  id: '/forge-mes',
  path: '/forge-mes',
  getParentRoute: () => SystemsRoute,
} as any)
const SystemsNexusCampusRoute = SystemsNexusCampusRouteImport.update({
  id: '/nexus-campus',
  path: '/nexus-campus',
  getParentRoute: () => SystemsRoute,
} as any)
const SystemsPrismImpactRoute = SystemsPrismImpactRouteImport.update({
  id: '/prism-impact',
  path: '/prism-impact',
  getParentRoute: () => SystemsRoute,
} as any)
const SystemsPulseOsRoute = SystemsPulseOsRouteImport.update({
  id: '/pulse-os',
  path: '/pulse-os',
  getParentRoute: () => SystemsRoute,
} as any)
const SystemsStrataOpsRoute = SystemsStrataOpsRouteImport.update({
  id: '/strata-ops',
  path: '/strata-ops',
  getParentRoute: () => SystemsRoute,
} as any)
const SystemsTalentGridRoute = SystemsTalentGridRouteImport.update({
  id: '/talent-grid',
  path: '/talent-grid',
  getParentRoute: () => SystemsRoute,
} as any)
const SystemsVectorDispatchRoute = SystemsVectorDispatchRouteImport.update({
  id: '/vector-dispatch',
  path: '/vector-dispatch',
  getParentRoute: () => SystemsRoute,
} as any)
const SystemsVeloxCommerceRoute = SystemsVeloxCommerceRouteImport.update({
  id: '/velox-commerce',
  path: '/velox-commerce',
  getParentRoute: () => SystemsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/architecture': typeof ArchitectureRoute
  '/contact': typeof ContactRoute
  '/founder': typeof FounderRoute
  '/systems': typeof SystemsRouteWithChildren
  '/systems/aura-hospitality': typeof SystemsAuraHospitalityRoute
  '/systems/civic-pulse': typeof SystemsCivicPulseRoute
  '/systems/construct-x': typeof SystemsConstructXRoute
  '/systems/equinox-ledger': typeof SystemsEquinoxLedgerRoute
  '/systems/forge-mes': typeof SystemsForgeMesRoute
  '/systems/nexus-campus': typeof SystemsNexusCampusRoute
  '/systems/prism-impact': typeof SystemsPrismImpactRoute
  '/systems/pulse-os': typeof SystemsPulseOsRoute
  '/systems/strata-ops': typeof SystemsStrataOpsRoute
  '/systems/talent-grid': typeof SystemsTalentGridRoute
  '/systems/vector-dispatch': typeof SystemsVectorDispatchRoute
  '/systems/velox-commerce': typeof SystemsVeloxCommerceRoute
  '/systems/': typeof SystemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/architecture': typeof ArchitectureRoute
  '/contact': typeof ContactRoute
  '/founder': typeof FounderRoute
  '/systems/aura-hospitality': typeof SystemsAuraHospitalityRoute
  '/systems/civic-pulse': typeof SystemsCivicPulseRoute
  '/systems/construct-x': typeof SystemsConstructXRoute
  '/systems/equinox-ledger': typeof SystemsEquinoxLedgerRoute
  '/systems/forge-mes': typeof SystemsForgeMesRoute
  '/systems/nexus-campus': typeof SystemsNexusCampusRoute
  '/systems/prism-impact': typeof SystemsPrismImpactRoute
  '/systems/pulse-os': typeof SystemsPulseOsRoute
  '/systems/strata-ops': typeof SystemsStrataOpsRoute
  '/systems/talent-grid': typeof SystemsTalentGridRoute
  '/systems/vector-dispatch': typeof SystemsVectorDispatchRoute
  '/systems/velox-commerce': typeof SystemsVeloxCommerceRoute
  '/systems': typeof SystemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/architecture': typeof ArchitectureRoute
  '/contact': typeof ContactRoute
  '/founder': typeof FounderRoute
  '/systems': typeof SystemsRouteWithChildren
  '/systems/aura-hospitality': typeof SystemsAuraHospitalityRoute
  '/systems/civic-pulse': typeof SystemsCivicPulseRoute
  '/systems/construct-x': typeof SystemsConstructXRoute
  '/systems/equinox-ledger': typeof SystemsEquinoxLedgerRoute
  '/systems/forge-mes': typeof SystemsForgeMesRoute
  '/systems/nexus-campus': typeof SystemsNexusCampusRoute
  '/systems/prism-impact': typeof SystemsPrismImpactRoute
  '/systems/pulse-os': typeof SystemsPulseOsRoute
  '/systems/strata-ops': typeof SystemsStrataOpsRoute
  '/systems/talent-grid': typeof SystemsTalentGridRoute
  '/systems/vector-dispatch': typeof SystemsVectorDispatchRoute
  '/systems/velox-commerce': typeof SystemsVeloxCommerceRoute
  '/systems/': typeof SystemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/architecture'
    | '/contact'
    | '/founder'
    | '/systems'
    | '/systems/aura-hospitality'
    | '/systems/civic-pulse'
    | '/systems/construct-x'
    | '/systems/equinox-ledger'
    | '/systems/forge-mes'
    | '/systems/nexus-campus'
    | '/systems/prism-impact'
    | '/systems/pulse-os'
    | '/systems/strata-ops'
    | '/systems/talent-grid'
    | '/systems/vector-dispatch'
    | '/systems/velox-commerce'
    | '/systems/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/architecture'
    | '/contact'
    | '/founder'
    | '/systems/aura-hospitality'
    | '/systems/civic-pulse'
    | '/systems/construct-x'
    | '/systems/equinox-ledger'
    | '/systems/forge-mes'
    | '/systems/nexus-campus'
    | '/systems/prism-impact'
    | '/systems/pulse-os'
    | '/systems/strata-ops'
    | '/systems/talent-grid'
    | '/systems/vector-dispatch'
    | '/systems/velox-commerce'
    | '/systems'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/architecture'
    | '/contact'
    | '/founder'
    | '/systems'
    | '/systems/aura-hospitality'
    | '/systems/civic-pulse'
    | '/systems/construct-x'
    | '/systems/equinox-ledger'
    | '/systems/forge-mes'
    | '/systems/nexus-campus'
    | '/systems/prism-impact'
    | '/systems/pulse-os'
    | '/systems/strata-ops'
    | '/systems/talent-grid'
    | '/systems/vector-dispatch'
    | '/systems/velox-commerce'
    | '/systems/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  ArchitectureRoute: typeof ArchitectureRoute
  ContactRoute: typeof ContactRoute
  FounderRoute: typeof FounderRoute
  SystemsRoute: typeof SystemsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems': {
      id: '/systems'
      path: '/systems'
      fullPath: '/systems'
      preLoaderRoute: typeof SystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems/': {
      id: '/systems/'
      path: '/'
      fullPath: '/systems/'
      preLoaderRoute: typeof SystemsIndexRouteImport
      parentRoute: typeof SystemsRoute
    }
    '/systems/aura-hospitality': {
      id: '/systems/aura-hospitality'
      path: '/aura-hospitality'
      fullPath: '/systems/aura-hospitality'
      preLoaderRoute: typeof SystemsAuraHospitalityRouteImport
      parentRoute: typeof SystemsRoute
    }
    '/systems/civic-pulse': {
      id: '/systems/civic-pulse'
      path: '/civic-pulse'
      fullPath: '/systems/civic-pulse'
      preLoaderRoute: typeof SystemsCivicPulseRouteImport
      parentRoute: typeof SystemsRoute
    }
    '/systems/construct-x': {
      id: '/systems/construct-x'
      path: '/construct-x'
      fullPath: '/systems/construct-x'
      preLoaderRoute: typeof SystemsConstructXRouteImport
      parentRoute: typeof SystemsRoute
    }
    '/systems/equinox-ledger': {
      id: '/systems/equinox-ledger'
      path: '/equinox-ledger'
      fullPath: '/systems/equinox-ledger'
      preLoaderRoute: typeof SystemsEquinoxLedgerRouteImport
      parentRoute: typeof SystemsRoute
    }
    '/systems/forge-mes': {
      id: '/systems/forge-mes'
      path: '/forge-mes'
      fullPath: '/systems/forge-mes'
      preLoaderRoute: typeof SystemsForgeMesRouteImport
      parentRoute: typeof SystemsRoute
    }
    '/systems/nexus-campus': {
      id: '/systems/nexus-campus'
      path: '/nexus-campus'
      fullPath: '/systems/nexus-campus'
      preLoaderRoute: typeof SystemsNexusCampusRouteImport
      parentRoute: typeof SystemsRoute
    }
    '/systems/prism-impact': {
      id: '/systems/prism-impact'
      path: '/prism-impact'
      fullPath: '/systems/prism-impact'
      preLoaderRoute: typeof SystemsPrismImpactRouteImport
      parentRoute: typeof SystemsRoute
    }
    '/systems/pulse-os': {
      id: '/systems/pulse-os'
      path: '/pulse-os'
      fullPath: '/systems/pulse-os'
      preLoaderRoute: typeof SystemsPulseOsRouteImport
      parentRoute: typeof SystemsRoute
    }
    '/systems/strata-ops': {
      id: '/systems/strata-ops'
      path: '/strata-ops'
      fullPath: '/systems/strata-ops'
      preLoaderRoute: typeof SystemsStrataOpsRouteImport
      parentRoute: typeof SystemsRoute
    }
    '/systems/talent-grid': {
      id: '/systems/talent-grid'
      path: '/talent-grid'
      fullPath: '/systems/talent-grid'
      preLoaderRoute: typeof SystemsTalentGridRouteImport
      parentRoute: typeof SystemsRoute
    }
    '/systems/vector-dispatch': {
      id: '/systems/vector-dispatch'
      path: '/vector-dispatch'
      fullPath: '/systems/vector-dispatch'
      preLoaderRoute: typeof SystemsVectorDispatchRouteImport
      parentRoute: typeof SystemsRoute
    }
    '/systems/velox-commerce': {
      id: '/systems/velox-commerce'
      path: '/velox-commerce'
      fullPath: '/systems/velox-commerce'
      preLoaderRoute: typeof SystemsVeloxCommerceRouteImport
      parentRoute: typeof SystemsRoute
    }
  }
}

interface SystemsRouteChildren {
  SystemsAuraHospitalityRoute: typeof SystemsAuraHospitalityRoute
  SystemsCivicPulseRoute: typeof SystemsCivicPulseRoute
  SystemsConstructXRoute: typeof SystemsConstructXRoute
  SystemsEquinoxLedgerRoute: typeof SystemsEquinoxLedgerRoute
  SystemsForgeMesRoute: typeof SystemsForgeMesRoute
  SystemsNexusCampusRoute: typeof SystemsNexusCampusRoute
  SystemsPrismImpactRoute: typeof SystemsPrismImpactRoute
  SystemsPulseOsRoute: typeof SystemsPulseOsRoute
  SystemsStrataOpsRoute: typeof SystemsStrataOpsRoute
  SystemsTalentGridRoute: typeof SystemsTalentGridRoute
  SystemsVectorDispatchRoute: typeof SystemsVectorDispatchRoute
  SystemsVeloxCommerceRoute: typeof SystemsVeloxCommerceRoute
  SystemsIndexRoute: typeof SystemsIndexRoute
}

const SystemsRouteChildren: SystemsRouteChildren = {
  SystemsAuraHospitalityRoute: SystemsAuraHospitalityRoute,
  SystemsCivicPulseRoute: SystemsCivicPulseRoute,
  SystemsConstructXRoute: SystemsConstructXRoute,
  SystemsEquinoxLedgerRoute: SystemsEquinoxLedgerRoute,
  SystemsForgeMesRoute: SystemsForgeMesRoute,
  SystemsNexusCampusRoute: SystemsNexusCampusRoute,
  SystemsPrismImpactRoute: SystemsPrismImpactRoute,
  SystemsPulseOsRoute: SystemsPulseOsRoute,
  SystemsStrataOpsRoute: SystemsStrataOpsRoute,
  SystemsTalentGridRoute: SystemsTalentGridRoute,
  SystemsVectorDispatchRoute: SystemsVectorDispatchRoute,
  SystemsVeloxCommerceRoute: SystemsVeloxCommerceRoute,
  SystemsIndexRoute: SystemsIndexRoute,
}

const SystemsRouteWithChildren =
  SystemsRoute._addFileChildren(SystemsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  ArchitectureRoute: ArchitectureRoute,
  ContactRoute: ContactRoute,
  FounderRoute: FounderRoute,
  SystemsRoute: SystemsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
